// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5wGstQGeQkFUeMBXHxB4bP
// Component: bCkSoC7eAE
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 5wGstQGeQkFUeMBXHxB4bP/projectcss
import sty from "./PlasmicHomepage2.module.css"; // plasmic-import: bCkSoC7eAE/css

export const PlasmicHomepage2__VariantProps = new Array();

export const PlasmicHomepage2__ArgProps = new Array();

function PlasmicHomepage2__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"studentDashboard"}
            data-plasmic-override={overrides.studentDashboard}
            hasGap={true}
            className={classNames(projectcss.all, sty.studentDashboard)}
          >
            <div
              data-plasmic-name={"navigation"}
              data-plasmic-override={overrides.navigation}
              className={classNames(projectcss.all, sty.navigation)}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame95455"}
              data-plasmic-override={overrides.frame95455}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame95455)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"cardGoodMorning"}
                data-plasmic-override={overrides.cardGoodMorning}
                hasGap={true}
                className={classNames(projectcss.all, sty.cardGoodMorning)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"displayProfilePicture"}
                  data-plasmic-override={overrides.displayProfilePicture}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    sty.displayProfilePicture
                  )}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__siaMn
                  )}
                >
                  {"Good Morning, Aubrey."}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"cardOnboarding"}
                data-plasmic-override={overrides.cardOnboarding}
                hasGap={true}
                className={classNames(projectcss.all, sty.cardOnboarding)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"cardBodyCopy"}
                  data-plasmic-override={overrides.cardBodyCopy}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.cardBodyCopy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vDpG
                    )}
                  >
                    {"Onboarding"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__imlyW
                    )}
                  >
                    {
                      "Not sure how to use Tutorial Tim? Get started with our onboarding to learn the ins and out of the platforms abilities!"
                    }
                  </div>
                </p.Stack>

                <div
                  data-plasmic-name={"ctaRow"}
                  data-plasmic-override={overrides.ctaRow}
                  className={classNames(projectcss.all, sty.ctaRow)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonFormInlineTextDefault"}
                    data-plasmic-override={
                      overrides.buttonFormInlineTextDefault
                    }
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.buttonFormInlineTextDefault
                    )}
                  >
                    <div
                      data-plasmic-name={"label"}
                      data-plasmic-override={overrides.label}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label
                      )}
                    >
                      {"Get started"}
                    </div>
                  </p.Stack>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"whatsNew"}
                data-plasmic-override={overrides.whatsNew}
                hasGap={true}
                className={classNames(projectcss.all, sty.whatsNew)}
              >
                <div
                  data-plasmic-name={"section1"}
                  data-plasmic-override={overrides.section1}
                  className={classNames(projectcss.all, sty.section1)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"bodyCopy"}
                    data-plasmic-override={overrides.bodyCopy}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.bodyCopy)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mgKjD
                      )}
                    >
                      {"What’s new"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zIvRj
                      )}
                    >
                      {
                        "Check out the latest improvements the team at Tutorial Tim is working on and their blog. Here at Tutorial Tim, we are constantly seeking your insights."
                      }
                    </div>
                  </p.Stack>

                  <div
                    data-plasmic-name={"buttonRow"}
                    data-plasmic-override={overrides.buttonRow}
                    className={classNames(projectcss.all, sty.buttonRow)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"formInlineTextDefault"}
                      data-plasmic-override={overrides.formInlineTextDefault}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.formInlineTextDefault
                      )}
                    >
                      <div
                        data-plasmic-name={"label2"}
                        data-plasmic-override={overrides.label2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label2
                        )}
                      >
                        {"Changelog"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"formInlineTextDefault2"}
                      data-plasmic-override={overrides.formInlineTextDefault2}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.formInlineTextDefault2
                      )}
                    >
                      <div
                        data-plasmic-name={"label3"}
                        data-plasmic-override={overrides.label3}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label3
                        )}
                      >
                        {"Blog"}
                      </div>
                    </p.Stack>
                  </div>
                </div>

                <div
                  data-plasmic-name={"whatsNewImage"}
                  data-plasmic-override={overrides.whatsNewImage}
                  className={classNames(projectcss.all, sty.whatsNewImage)}
                />
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"continueLearningSection"}
              data-plasmic-override={overrides.continueLearningSection}
              hasGap={true}
              className={classNames(
                projectcss.all,
                sty.continueLearningSection
              )}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tqQpf
                )}
              >
                {"Continue Learning"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"cardsContinueLearningRow"}
                data-plasmic-override={overrides.cardsContinueLearningRow}
                hasGap={true}
                className={classNames(
                  projectcss.all,
                  sty.cardsContinueLearningRow
                )}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"goodMorning"}
                  data-plasmic-override={overrides.goodMorning}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.goodMorning)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"cardImage"}
                    data-plasmic-override={overrides.cardImage}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.cardImage)}
                  >
                    <div
                      data-plasmic-name={"image77"}
                      data-plasmic-override={overrides.image77}
                      className={classNames(projectcss.all, sty.image77)}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame95451"}
                    data-plasmic-override={overrides.frame95451}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame95451)}
                  >
                    <div
                      data-plasmic-name={"frame95452"}
                      data-plasmic-override={overrides.frame95452}
                      className={classNames(projectcss.all, sty.frame95452)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yZh0V
                        )}
                      >
                        {"Name of Course"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zrvSt
                        )}
                      >
                        {"Title of Video"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qKgdm
                      )}
                    >
                      {
                        "Get right back to learning where you left off. You’re 28% of the way there!"
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonContainer"}
                    data-plasmic-override={overrides.buttonContainer}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttonContainer)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lZjDv
                        )}
                      >
                        {"Resume"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"goodMorning2"}
                  data-plasmic-override={overrides.goodMorning2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.goodMorning2)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"cardImage2"}
                    data-plasmic-override={overrides.cardImage2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.cardImage2)}
                  >
                    <div
                      data-plasmic-name={"image78"}
                      data-plasmic-override={overrides.image78}
                      className={classNames(projectcss.all, sty.image78)}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame95453"}
                    data-plasmic-override={overrides.frame95453}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame95453)}
                  >
                    <div
                      data-plasmic-name={"frame95454"}
                      data-plasmic-override={overrides.frame95454}
                      className={classNames(projectcss.all, sty.frame95454)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aQSm
                        )}
                      >
                        {"Name of Course"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hKyO
                        )}
                      >
                        {"Title of Video"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wAkUk
                      )}
                    >
                      {
                        "Get right back to learning where you left off. You’re 28% of the way there!"
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonContainer2"}
                    data-plasmic-override={overrides.buttonContainer2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttonContainer2)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button2"}
                      data-plasmic-override={overrides.button2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__c6Kz
                        )}
                      >
                        {"Resume"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"goodMorning3"}
                  data-plasmic-override={overrides.goodMorning3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.goodMorning3)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"cardImage3"}
                    data-plasmic-override={overrides.cardImage3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.cardImage3)}
                  >
                    <div
                      data-plasmic-name={"image79"}
                      data-plasmic-override={overrides.image79}
                      className={classNames(projectcss.all, sty.image79)}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame95456"}
                    data-plasmic-override={overrides.frame95456}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame95456)}
                  >
                    <div
                      data-plasmic-name={"frame95457"}
                      data-plasmic-override={overrides.frame95457}
                      className={classNames(projectcss.all, sty.frame95457)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xh9YL
                        )}
                      >
                        {"Name of Course"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pg7Nc
                        )}
                      >
                        {"Title of Video"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hkHde
                      )}
                    >
                      {
                        "Get right back to learning where you left off. You’re 28% of the way there!"
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonContainer3"}
                    data-plasmic-override={overrides.buttonContainer3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttonContainer3)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button3"}
                      data-plasmic-override={overrides.button3}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__psFdb
                        )}
                      >
                        {"Resume"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"goodMorning4"}
                  data-plasmic-override={overrides.goodMorning4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.goodMorning4)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"cardImage4"}
                    data-plasmic-override={overrides.cardImage4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.cardImage4)}
                  >
                    <div
                      data-plasmic-name={"image80"}
                      data-plasmic-override={overrides.image80}
                      className={classNames(projectcss.all, sty.image80)}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame95458"}
                    data-plasmic-override={overrides.frame95458}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame95458)}
                  >
                    <div
                      data-plasmic-name={"frame95459"}
                      data-plasmic-override={overrides.frame95459}
                      className={classNames(projectcss.all, sty.frame95459)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__auMcl
                        )}
                      >
                        {"Name of Course"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zxh2T
                        )}
                      >
                        {"Title of Video"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Lk7A
                      )}
                    >
                      {
                        "Get right back to learning where you left off. You’re 28% of the way there!"
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonContainer4"}
                    data-plasmic-override={overrides.buttonContainer4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttonContainer4)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button4"}
                      data-plasmic-override={overrides.button4}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8Od4X
                        )}
                      >
                        {"Resume"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"continueLearningSection2"}
              data-plasmic-override={overrides.continueLearningSection2}
              hasGap={true}
              className={classNames(
                projectcss.all,
                sty.continueLearningSection2
              )}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qgNgt
                )}
              >
                {"Featured Courses"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"cardsContinueLearningRow2"}
                data-plasmic-override={overrides.cardsContinueLearningRow2}
                hasGap={true}
                className={classNames(
                  projectcss.all,
                  sty.cardsContinueLearningRow2
                )}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"goodMorning5"}
                  data-plasmic-override={overrides.goodMorning5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.goodMorning5)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"cardImage5"}
                    data-plasmic-override={overrides.cardImage5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.cardImage5)}
                  >
                    <div
                      data-plasmic-name={"image81"}
                      data-plasmic-override={overrides.image81}
                      className={classNames(projectcss.all, sty.image81)}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame95460"}
                    data-plasmic-override={overrides.frame95460}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame95460)}
                  >
                    <div
                      data-plasmic-name={"frame95461"}
                      data-plasmic-override={overrides.frame95461}
                      className={classNames(projectcss.all, sty.frame95461)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__u5OnP
                        )}
                      >
                        {"Name of Course"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__smkql
                        )}
                      >
                        {"Title of Video"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kEBk
                      )}
                    >
                      {
                        "Mini description of the course which hasn’t been bought by user yet."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonContainer5"}
                    data-plasmic-override={overrides.buttonContainer5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttonContainer5)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button5"}
                      data-plasmic-override={overrides.button5}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___16AG6
                        )}
                      >
                        {"Buy"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"goodMorning6"}
                  data-plasmic-override={overrides.goodMorning6}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.goodMorning6)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"cardImage6"}
                    data-plasmic-override={overrides.cardImage6}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.cardImage6)}
                  >
                    <div
                      data-plasmic-name={"image82"}
                      data-plasmic-override={overrides.image82}
                      className={classNames(projectcss.all, sty.image82)}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame95462"}
                    data-plasmic-override={overrides.frame95462}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame95462)}
                  >
                    <div
                      data-plasmic-name={"frame95463"}
                      data-plasmic-override={overrides.frame95463}
                      className={classNames(projectcss.all, sty.frame95463)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wizQ4
                        )}
                      >
                        {"Name of Course"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ooyfu
                        )}
                      >
                        {"Title of Video"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iofOv
                      )}
                    >
                      {
                        "Mini description of the course which hasn’t been bought by user yet."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonContainer6"}
                    data-plasmic-override={overrides.buttonContainer6}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttonContainer6)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button6"}
                      data-plasmic-override={overrides.button6}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button6)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bGpLe
                        )}
                      >
                        {"Buy"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"goodMorning7"}
                  data-plasmic-override={overrides.goodMorning7}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.goodMorning7)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"cardImage7"}
                    data-plasmic-override={overrides.cardImage7}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.cardImage7)}
                  >
                    <div
                      data-plasmic-name={"image83"}
                      data-plasmic-override={overrides.image83}
                      className={classNames(projectcss.all, sty.image83)}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame95464"}
                    data-plasmic-override={overrides.frame95464}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame95464)}
                  >
                    <div
                      data-plasmic-name={"frame95465"}
                      data-plasmic-override={overrides.frame95465}
                      className={classNames(projectcss.all, sty.frame95465)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__p0Vzd
                        )}
                      >
                        {"Name of Course"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__naged
                        )}
                      >
                        {"Title of Video"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__p6Erm
                      )}
                    >
                      {
                        "Mini description of the course which hasn’t been bought by user yet."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonContainer7"}
                    data-plasmic-override={overrides.buttonContainer7}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttonContainer7)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button7"}
                      data-plasmic-override={overrides.button7}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cWZi5
                        )}
                      >
                        {"Buy"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"goodMorning8"}
                  data-plasmic-override={overrides.goodMorning8}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.goodMorning8)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"cardImage8"}
                    data-plasmic-override={overrides.cardImage8}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.cardImage8)}
                  >
                    <div
                      data-plasmic-name={"image84"}
                      data-plasmic-override={overrides.image84}
                      className={classNames(projectcss.all, sty.image84)}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame95466"}
                    data-plasmic-override={overrides.frame95466}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame95466)}
                  >
                    <div
                      data-plasmic-name={"frame95467"}
                      data-plasmic-override={overrides.frame95467}
                      className={classNames(projectcss.all, sty.frame95467)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pGx0P
                        )}
                      >
                        {"Name of Course"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zFlUe
                        )}
                      >
                        {"Title of Video"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__beF0X
                      )}
                    >
                      {
                        "Mini description of the course which hasn’t been bought by user yet."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttonContainer8"}
                    data-plasmic-override={overrides.buttonContainer8}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttonContainer8)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button8"}
                      data-plasmic-override={overrides.button8}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qBgXf
                        )}
                      >
                        {"Buy"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </p.Stack>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "studentDashboard",
    "navigation",
    "frame95455",
    "cardGoodMorning",
    "displayProfilePicture",
    "cardOnboarding",
    "cardBodyCopy",
    "ctaRow",
    "buttonFormInlineTextDefault",
    "label",
    "whatsNew",
    "section1",
    "bodyCopy",
    "buttonRow",
    "formInlineTextDefault",
    "label2",
    "formInlineTextDefault2",
    "label3",
    "whatsNewImage",
    "continueLearningSection",
    "cardsContinueLearningRow",
    "goodMorning",
    "cardImage",
    "image77",
    "frame95451",
    "frame95452",
    "buttonContainer",
    "button",
    "goodMorning2",
    "cardImage2",
    "image78",
    "frame95453",
    "frame95454",
    "buttonContainer2",
    "button2",
    "goodMorning3",
    "cardImage3",
    "image79",
    "frame95456",
    "frame95457",
    "buttonContainer3",
    "button3",
    "goodMorning4",
    "cardImage4",
    "image80",
    "frame95458",
    "frame95459",
    "buttonContainer4",
    "button4",
    "continueLearningSection2",
    "cardsContinueLearningRow2",
    "goodMorning5",
    "cardImage5",
    "image81",
    "frame95460",
    "frame95461",
    "buttonContainer5",
    "button5",
    "goodMorning6",
    "cardImage6",
    "image82",
    "frame95462",
    "frame95463",
    "buttonContainer6",
    "button6",
    "goodMorning7",
    "cardImage7",
    "image83",
    "frame95464",
    "frame95465",
    "buttonContainer7",
    "button7",
    "goodMorning8",
    "cardImage8",
    "image84",
    "frame95466",
    "frame95467",
    "buttonContainer8",
    "button8"
  ],

  studentDashboard: [
    "studentDashboard",
    "navigation",
    "frame95455",
    "cardGoodMorning",
    "displayProfilePicture",
    "cardOnboarding",
    "cardBodyCopy",
    "ctaRow",
    "buttonFormInlineTextDefault",
    "label",
    "whatsNew",
    "section1",
    "bodyCopy",
    "buttonRow",
    "formInlineTextDefault",
    "label2",
    "formInlineTextDefault2",
    "label3",
    "whatsNewImage",
    "continueLearningSection",
    "cardsContinueLearningRow",
    "goodMorning",
    "cardImage",
    "image77",
    "frame95451",
    "frame95452",
    "buttonContainer",
    "button",
    "goodMorning2",
    "cardImage2",
    "image78",
    "frame95453",
    "frame95454",
    "buttonContainer2",
    "button2",
    "goodMorning3",
    "cardImage3",
    "image79",
    "frame95456",
    "frame95457",
    "buttonContainer3",
    "button3",
    "goodMorning4",
    "cardImage4",
    "image80",
    "frame95458",
    "frame95459",
    "buttonContainer4",
    "button4",
    "continueLearningSection2",
    "cardsContinueLearningRow2",
    "goodMorning5",
    "cardImage5",
    "image81",
    "frame95460",
    "frame95461",
    "buttonContainer5",
    "button5",
    "goodMorning6",
    "cardImage6",
    "image82",
    "frame95462",
    "frame95463",
    "buttonContainer6",
    "button6",
    "goodMorning7",
    "cardImage7",
    "image83",
    "frame95464",
    "frame95465",
    "buttonContainer7",
    "button7",
    "goodMorning8",
    "cardImage8",
    "image84",
    "frame95466",
    "frame95467",
    "buttonContainer8",
    "button8"
  ],

  navigation: ["navigation"],
  frame95455: [
    "frame95455",
    "cardGoodMorning",
    "displayProfilePicture",
    "cardOnboarding",
    "cardBodyCopy",
    "ctaRow",
    "buttonFormInlineTextDefault",
    "label",
    "whatsNew",
    "section1",
    "bodyCopy",
    "buttonRow",
    "formInlineTextDefault",
    "label2",
    "formInlineTextDefault2",
    "label3",
    "whatsNewImage"
  ],

  cardGoodMorning: ["cardGoodMorning", "displayProfilePicture"],
  displayProfilePicture: ["displayProfilePicture"],
  cardOnboarding: [
    "cardOnboarding",
    "cardBodyCopy",
    "ctaRow",
    "buttonFormInlineTextDefault",
    "label"
  ],

  cardBodyCopy: ["cardBodyCopy"],
  ctaRow: ["ctaRow", "buttonFormInlineTextDefault", "label"],
  buttonFormInlineTextDefault: ["buttonFormInlineTextDefault", "label"],
  label: ["label"],
  whatsNew: [
    "whatsNew",
    "section1",
    "bodyCopy",
    "buttonRow",
    "formInlineTextDefault",
    "label2",
    "formInlineTextDefault2",
    "label3",
    "whatsNewImage"
  ],

  section1: [
    "section1",
    "bodyCopy",
    "buttonRow",
    "formInlineTextDefault",
    "label2",
    "formInlineTextDefault2",
    "label3"
  ],

  bodyCopy: ["bodyCopy"],
  buttonRow: [
    "buttonRow",
    "formInlineTextDefault",
    "label2",
    "formInlineTextDefault2",
    "label3"
  ],

  formInlineTextDefault: ["formInlineTextDefault", "label2"],
  label2: ["label2"],
  formInlineTextDefault2: ["formInlineTextDefault2", "label3"],
  label3: ["label3"],
  whatsNewImage: ["whatsNewImage"],
  continueLearningSection: [
    "continueLearningSection",
    "cardsContinueLearningRow",
    "goodMorning",
    "cardImage",
    "image77",
    "frame95451",
    "frame95452",
    "buttonContainer",
    "button",
    "goodMorning2",
    "cardImage2",
    "image78",
    "frame95453",
    "frame95454",
    "buttonContainer2",
    "button2",
    "goodMorning3",
    "cardImage3",
    "image79",
    "frame95456",
    "frame95457",
    "buttonContainer3",
    "button3",
    "goodMorning4",
    "cardImage4",
    "image80",
    "frame95458",
    "frame95459",
    "buttonContainer4",
    "button4"
  ],

  cardsContinueLearningRow: [
    "cardsContinueLearningRow",
    "goodMorning",
    "cardImage",
    "image77",
    "frame95451",
    "frame95452",
    "buttonContainer",
    "button",
    "goodMorning2",
    "cardImage2",
    "image78",
    "frame95453",
    "frame95454",
    "buttonContainer2",
    "button2",
    "goodMorning3",
    "cardImage3",
    "image79",
    "frame95456",
    "frame95457",
    "buttonContainer3",
    "button3",
    "goodMorning4",
    "cardImage4",
    "image80",
    "frame95458",
    "frame95459",
    "buttonContainer4",
    "button4"
  ],

  goodMorning: [
    "goodMorning",
    "cardImage",
    "image77",
    "frame95451",
    "frame95452",
    "buttonContainer",
    "button"
  ],

  cardImage: ["cardImage", "image77"],
  image77: ["image77"],
  frame95451: ["frame95451", "frame95452"],
  frame95452: ["frame95452"],
  buttonContainer: ["buttonContainer", "button"],
  button: ["button"],
  goodMorning2: [
    "goodMorning2",
    "cardImage2",
    "image78",
    "frame95453",
    "frame95454",
    "buttonContainer2",
    "button2"
  ],

  cardImage2: ["cardImage2", "image78"],
  image78: ["image78"],
  frame95453: ["frame95453", "frame95454"],
  frame95454: ["frame95454"],
  buttonContainer2: ["buttonContainer2", "button2"],
  button2: ["button2"],
  goodMorning3: [
    "goodMorning3",
    "cardImage3",
    "image79",
    "frame95456",
    "frame95457",
    "buttonContainer3",
    "button3"
  ],

  cardImage3: ["cardImage3", "image79"],
  image79: ["image79"],
  frame95456: ["frame95456", "frame95457"],
  frame95457: ["frame95457"],
  buttonContainer3: ["buttonContainer3", "button3"],
  button3: ["button3"],
  goodMorning4: [
    "goodMorning4",
    "cardImage4",
    "image80",
    "frame95458",
    "frame95459",
    "buttonContainer4",
    "button4"
  ],

  cardImage4: ["cardImage4", "image80"],
  image80: ["image80"],
  frame95458: ["frame95458", "frame95459"],
  frame95459: ["frame95459"],
  buttonContainer4: ["buttonContainer4", "button4"],
  button4: ["button4"],
  continueLearningSection2: [
    "continueLearningSection2",
    "cardsContinueLearningRow2",
    "goodMorning5",
    "cardImage5",
    "image81",
    "frame95460",
    "frame95461",
    "buttonContainer5",
    "button5",
    "goodMorning6",
    "cardImage6",
    "image82",
    "frame95462",
    "frame95463",
    "buttonContainer6",
    "button6",
    "goodMorning7",
    "cardImage7",
    "image83",
    "frame95464",
    "frame95465",
    "buttonContainer7",
    "button7",
    "goodMorning8",
    "cardImage8",
    "image84",
    "frame95466",
    "frame95467",
    "buttonContainer8",
    "button8"
  ],

  cardsContinueLearningRow2: [
    "cardsContinueLearningRow2",
    "goodMorning5",
    "cardImage5",
    "image81",
    "frame95460",
    "frame95461",
    "buttonContainer5",
    "button5",
    "goodMorning6",
    "cardImage6",
    "image82",
    "frame95462",
    "frame95463",
    "buttonContainer6",
    "button6",
    "goodMorning7",
    "cardImage7",
    "image83",
    "frame95464",
    "frame95465",
    "buttonContainer7",
    "button7",
    "goodMorning8",
    "cardImage8",
    "image84",
    "frame95466",
    "frame95467",
    "buttonContainer8",
    "button8"
  ],

  goodMorning5: [
    "goodMorning5",
    "cardImage5",
    "image81",
    "frame95460",
    "frame95461",
    "buttonContainer5",
    "button5"
  ],

  cardImage5: ["cardImage5", "image81"],
  image81: ["image81"],
  frame95460: ["frame95460", "frame95461"],
  frame95461: ["frame95461"],
  buttonContainer5: ["buttonContainer5", "button5"],
  button5: ["button5"],
  goodMorning6: [
    "goodMorning6",
    "cardImage6",
    "image82",
    "frame95462",
    "frame95463",
    "buttonContainer6",
    "button6"
  ],

  cardImage6: ["cardImage6", "image82"],
  image82: ["image82"],
  frame95462: ["frame95462", "frame95463"],
  frame95463: ["frame95463"],
  buttonContainer6: ["buttonContainer6", "button6"],
  button6: ["button6"],
  goodMorning7: [
    "goodMorning7",
    "cardImage7",
    "image83",
    "frame95464",
    "frame95465",
    "buttonContainer7",
    "button7"
  ],

  cardImage7: ["cardImage7", "image83"],
  image83: ["image83"],
  frame95464: ["frame95464", "frame95465"],
  frame95465: ["frame95465"],
  buttonContainer7: ["buttonContainer7", "button7"],
  button7: ["button7"],
  goodMorning8: [
    "goodMorning8",
    "cardImage8",
    "image84",
    "frame95466",
    "frame95467",
    "buttonContainer8",
    "button8"
  ],

  cardImage8: ["cardImage8", "image84"],
  image84: ["image84"],
  frame95466: ["frame95466", "frame95467"],
  frame95467: ["frame95467"],
  buttonContainer8: ["buttonContainer8", "button8"],
  button8: ["button8"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage2__ArgProps,
      internalVariantPropNames: PlasmicHomepage2__VariantProps
    });

    return PlasmicHomepage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage2";
  } else {
    func.displayName = `PlasmicHomepage2.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage2 = Object.assign(
  // Top-level PlasmicHomepage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    studentDashboard: makeNodeComponent("studentDashboard"),
    navigation: makeNodeComponent("navigation"),
    frame95455: makeNodeComponent("frame95455"),
    cardGoodMorning: makeNodeComponent("cardGoodMorning"),
    displayProfilePicture: makeNodeComponent("displayProfilePicture"),
    cardOnboarding: makeNodeComponent("cardOnboarding"),
    cardBodyCopy: makeNodeComponent("cardBodyCopy"),
    ctaRow: makeNodeComponent("ctaRow"),
    buttonFormInlineTextDefault: makeNodeComponent(
      "buttonFormInlineTextDefault"
    ),

    label: makeNodeComponent("label"),
    whatsNew: makeNodeComponent("whatsNew"),
    section1: makeNodeComponent("section1"),
    bodyCopy: makeNodeComponent("bodyCopy"),
    buttonRow: makeNodeComponent("buttonRow"),
    formInlineTextDefault: makeNodeComponent("formInlineTextDefault"),
    label2: makeNodeComponent("label2"),
    formInlineTextDefault2: makeNodeComponent("formInlineTextDefault2"),
    label3: makeNodeComponent("label3"),
    whatsNewImage: makeNodeComponent("whatsNewImage"),
    continueLearningSection: makeNodeComponent("continueLearningSection"),
    cardsContinueLearningRow: makeNodeComponent("cardsContinueLearningRow"),
    goodMorning: makeNodeComponent("goodMorning"),
    cardImage: makeNodeComponent("cardImage"),
    image77: makeNodeComponent("image77"),
    frame95451: makeNodeComponent("frame95451"),
    frame95452: makeNodeComponent("frame95452"),
    buttonContainer: makeNodeComponent("buttonContainer"),
    button: makeNodeComponent("button"),
    goodMorning2: makeNodeComponent("goodMorning2"),
    cardImage2: makeNodeComponent("cardImage2"),
    image78: makeNodeComponent("image78"),
    frame95453: makeNodeComponent("frame95453"),
    frame95454: makeNodeComponent("frame95454"),
    buttonContainer2: makeNodeComponent("buttonContainer2"),
    button2: makeNodeComponent("button2"),
    goodMorning3: makeNodeComponent("goodMorning3"),
    cardImage3: makeNodeComponent("cardImage3"),
    image79: makeNodeComponent("image79"),
    frame95456: makeNodeComponent("frame95456"),
    frame95457: makeNodeComponent("frame95457"),
    buttonContainer3: makeNodeComponent("buttonContainer3"),
    button3: makeNodeComponent("button3"),
    goodMorning4: makeNodeComponent("goodMorning4"),
    cardImage4: makeNodeComponent("cardImage4"),
    image80: makeNodeComponent("image80"),
    frame95458: makeNodeComponent("frame95458"),
    frame95459: makeNodeComponent("frame95459"),
    buttonContainer4: makeNodeComponent("buttonContainer4"),
    button4: makeNodeComponent("button4"),
    continueLearningSection2: makeNodeComponent("continueLearningSection2"),
    cardsContinueLearningRow2: makeNodeComponent("cardsContinueLearningRow2"),
    goodMorning5: makeNodeComponent("goodMorning5"),
    cardImage5: makeNodeComponent("cardImage5"),
    image81: makeNodeComponent("image81"),
    frame95460: makeNodeComponent("frame95460"),
    frame95461: makeNodeComponent("frame95461"),
    buttonContainer5: makeNodeComponent("buttonContainer5"),
    button5: makeNodeComponent("button5"),
    goodMorning6: makeNodeComponent("goodMorning6"),
    cardImage6: makeNodeComponent("cardImage6"),
    image82: makeNodeComponent("image82"),
    frame95462: makeNodeComponent("frame95462"),
    frame95463: makeNodeComponent("frame95463"),
    buttonContainer6: makeNodeComponent("buttonContainer6"),
    button6: makeNodeComponent("button6"),
    goodMorning7: makeNodeComponent("goodMorning7"),
    cardImage7: makeNodeComponent("cardImage7"),
    image83: makeNodeComponent("image83"),
    frame95464: makeNodeComponent("frame95464"),
    frame95465: makeNodeComponent("frame95465"),
    buttonContainer7: makeNodeComponent("buttonContainer7"),
    button7: makeNodeComponent("button7"),
    goodMorning8: makeNodeComponent("goodMorning8"),
    cardImage8: makeNodeComponent("cardImage8"),
    image84: makeNodeComponent("image84"),
    frame95466: makeNodeComponent("frame95466"),
    frame95467: makeNodeComponent("frame95467"),
    buttonContainer8: makeNodeComponent("buttonContainer8"),
    button8: makeNodeComponent("button8"),
    // Metadata about props expected for PlasmicHomepage2
    internalVariantProps: PlasmicHomepage2__VariantProps,
    internalArgProps: PlasmicHomepage2__ArgProps
  }
);

export default PlasmicHomepage2;
/* prettier-ignore-end */
